Update buildAndDeploy.yml

diff --git a/.github/workflows/buildAndDeploy.yml b/.github/workflows/buildAndDeploy.yml
--- a/.github/workflows/buildAndDeploy.yml
+++ b/.github/workflows/buildAndDeploy.yml
@@ -32,9 +32,15 @@ jobs:
           temp_toml_file=$(mktemp -t wrangler-temp.XXXXXX.toml)
           echo "temp_toml_file=$temp_toml_file" >> $GITHUB_ENV  # Add to environment
 
-      - name: Define temp_toml_file Environment Variable
+      - name: Verify Temporary File
         run: |
-          cat "$env.temp_toml_file"
+          if [ -f "$env.temp_toml_file" ]; then
+            echo "Temporary file created successfully: $env.temp_toml_file"
+            cat "$env.temp_toml_file"
+          else
+            echo "Error: Temporary file creation failed!"
+            exit 1
+          fi
 
       - name: Deploy
         uses: cloudflare/wrangler-action@v3
